import React, { useMemo, useRef, useState } from 'react';
import { EXPERIENCE_BANDS, TASTER_QUESTIONS, computeTasterResult, VALU_VERSION } from './valuTaster.js';

const CLUSTERS={P:'Presence',R:'Relationships',I:'Intelligence',M:'Mastery',E:'Enterprise'};
const COLORS={P:'#1D9E75',R:'#378ADD',I:'#7F77DD',M:'#BA7517',E:'#D85A30'};
const DARK='#0F0F1A', PARCH='#F7F4EE', GOLD='#C9A84C', DIM='rgba(247,244,238,.5)';

export default function VALUIndexV4GateNext(){
 const [phase,setPhase]=useState('intro');
 const [name,setName]=useState(''); const [role,setRole]=useState(''); const [experience,setExperience]=useState('');
 const [current,setCurrent]=useState(0); const [answers,setAnswers]=useState({}); const [selected,setSelected]=useState(null);
 const [result,setResult]=useState(null); const [tasterId,setTasterId]=useState(''); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
 const q=TASTER_QUESTIONS[current];
 const progress=Math.round(((current+1)/TASTER_QUESTIONS.length)*100);
 const scores=useMemo(()=>result?Object.entries(result.normalisedScores).sort((a,b)=>b[1]-a[1]):[],[result]);
 function start(){ if(!name.trim()||!role.trim()||!experience)return; setCurrent(0);setAnswers({});setSelected(null);setError('');setPhase('taster'); }
 async function answer(index){
  const next={...answers,[current]:index}; setAnswers(next);
  if(current<TASTER_QUESTIONS.length-1){setTimeout(()=>{setCurrent(v=>v+1);setSelected(null)},180);return;}
  setSaving(true);setError('');
  try{
   const response=await fetch('/api/submit-taster',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:name.trim(),role:role.trim(),experience,answers:next})});
   const data=await response.json().catch(()=>({}));
   if(!response.ok)throw new Error(data.error||'Your snapshot could not be saved.');
   setResult(data.results || computeTasterResult(next)); setTasterId(data.taster_id||''); setPhase('results');
  }catch(err){setError(err?.message||'Something went wrong.');}
  finally{setSaving(false);setSelected(null);}
 }
 function choose(i){if(selected!==null||saving)return;setSelected(i);setTimeout(()=>answer(i),120)}
 if(phase==='intro')return <Shell><div style={S.brand}>VALORIA INSTITUTE · AFRICAN TALENT BUREAU</div><h1 style={S.hero}>The <em>VALU</em> Index</h1><p style={S.lead}>Find out where you stand — and where your professional capabilities take you.</p><div style={S.card}><div style={S.eyebrow}>START HERE</div><h2 style={S.cardTitle}>15-question VALU snapshot</h2><p style={S.p}>A directional capability read across Presence, Relationships, Intelligence, Mastery and Enterprise. It is a teaser, not your official VALU Index.</p><div style={S.pills}>{['15 questions','Instant summary','Free'].map(x=><span key={x}>{x}</span>)}</div></div><div style={S.form}><label>FULL NAME<input value={name} onChange={e=>setName(e.target.value)} placeholder="Your full professional name"/></label><label>CURRENT ROLE<input value={role} onChange={e=>setRole(e.target.value)} placeholder="e.g. Senior Product Manager"/></label><label>PROFESSIONAL EXPERIENCE<select value={experience} onChange={e=>setExperience(e.target.value)}><option value="">Select your experience</option>{EXPERIENCE_BANDS.map(x=><option key={x.id} value={x.id}>{x.label} · {x.desc}</option>)}</select></label><button disabled={!name.trim()||!role.trim()||!experience} onClick={start}>START THE 15-QUESTION SNAPSHOT →</button></div><p style={S.note}>VALU v{VALU_VERSION} · The 15-question result never becomes your official score.</p></Shell>;
 if(phase==='taster')return <Shell><div style={S.top}><div style={S.eyebrow}>{q.cluster} · {CLUSTERS[q.cluster]}</div><div style={S.counter}>{current+1} / {TASTER_QUESTIONS.length}</div></div><div style={S.progress}><div style={{...S.fill,width:`${progress}%`,background:COLORS[q.cluster]}}/></div><div style={S.insight}>{q.tasterInsight}</div><h1 style={S.question}>{q.q}</h1><div style={S.options}>{q.options.map((o,i)=><button key={i} disabled={selected!==null||saving} onClick={()=>choose(i)} style={{...S.option,borderColor:selected===i?GOLD:'rgba(247,244,238,.1)',background:selected===i?'rgba(201,168,76,.08)':'rgba(255,255,255,.025)'}}><span>{String.fromCharCode(65+i)}</span>{o.text}</button>)}</div>{error&&<div style={S.error}>{error}</div>}</Shell>;
 const signupUrl=`https://valoriainstitute.com/professional-signup?taster_id=${encodeURIComponent(tasterId)}&name=${encodeURIComponent(name)}&role=${encodeURIComponent(role)}&experience=${encodeURIComponent(experience)}`;
 return <Shell><div style={S.eyebrow}>YOUR SNAPSHOT</div><h1 style={S.h1}>You have a direction.<br/><em>Now make it official.</em></h1><p style={S.p}>This is your 15-question directional read. Your official VALU Index is only established by the full assessment.</p><div style={S.resultGrid}>{scores.map(([id,value])=><div key={id} style={S.resultRow}><div><b style={{color:COLORS[id]}}>{id}</b> <span>{CLUSTERS[id]}</span></div><strong>{value}</strong></div>)}</div><div style={S.highlight}><div style={S.eyebrow}>YOUR SNAPSHOT SIGNAL</div><div style={S.signal}><span style={{color:COLORS[result.strongest.id]}}>{result.strongest.name}</span><span>is currently strongest.</span></div><div style={S.weak}>Your lowest directional signal is {result.weakest.name}. The full assessment will establish the official score across all PRIME dimensions.</div></div><div style={S.next}><div style={S.eyebrow}>NEXT</div><h2>Create your Valoria account.</h2><p>Your profile will be temporarily listed as <strong style={{color:GOLD}}>Basic · Incomplete</strong>. Then complete the full assessment to establish your official VALU Index.</p><a href={signupUrl}>CREATE ACCOUNT & CONTINUE →</a></div><p style={S.note}>Your teaser result is saved. It does not count toward the official VALU Index.</p></Shell>;
}

function Shell({children}){return <main style={S.page}><div style={S.shell}>{children}</div></main>}
const S={
 page:{minHeight:'100vh',background:DARK,color:PARCH,padding:'clamp(28px,6vw,72px) 20px',fontFamily:"'Raleway',sans-serif"},shell:{maxWidth:760,margin:'0 auto'},brand:{fontSize:10,fontWeight:700,letterSpacing:'.18em',color:GOLD,textAlign:'center'},hero:{fontSize:'clamp(48px,8vw,82px)',fontWeight:300,lineHeight:1,letterSpacing:'-.04em',textAlign:'center',margin:'18px 0 14px'},lead:{fontSize:15,lineHeight:1.7,color:DIM,textAlign:'center',margin:'0 auto 30px',maxWidth:600},card:{border:'1px solid rgba(201,168,76,.2)',background:'rgba(201,168,76,.05)',padding:22,borderRadius:9},eyebrow:{fontSize:9,fontWeight:700,letterSpacing:'.18em',color:'rgba(201,168,76,.72)',textTransform:'uppercase'},cardTitle:{fontSize:21,fontWeight:400,margin:'8px 0 7px'},p:{fontSize:13,lineHeight:1.7,color:DIM},pills:{display:'flex',gap:7,flexWrap:'wrap',marginTop:14},form:{display:'grid',gap:13,marginTop:22},formLabel:{fontSize:10},options:{display:'grid',gap:10},option:{display:'grid',gridTemplateColumns:'30px 1fr',gap:13,textAlign:'left',padding:'16px',border:'1px solid',borderRadius:8,color:PARCH,fontSize:14,lineHeight:1.55,cursor:'pointer'},top:{display:'flex',justifyContent:'space-between'},counter:{fontSize:11,color:'rgba(247,244,238,.3)'},progress:{height:3,background:'rgba(255,255,255,.06)',margin:'16px 0 30px'},fill:{height:'100%'},insight:{fontSize:11,color:'rgba(247,244,238,.38)',marginBottom:12},question:{fontSize:'clamp(28px,5vw,46px)',fontWeight:300,lineHeight:1.15,letterSpacing:'-.025em',margin:'0 0 28px'},h1:{fontSize:'clamp(38px,7vw,64px)',fontWeight:300,lineHeight:1.04,letterSpacing:'-.035em',margin:'0 0 16px'},resultGrid:{display:'grid',gridTemplateColumns:'repeat(5,1fr)',gap:7,margin:'26px 0'},resultRow:{padding:'13px 9px',border:'1px solid rgba(247,244,238,.08)',borderRadius:7,textAlign:'center',fontSize:11},highlight:{padding:20,border:'1px solid rgba(201,168,76,.18)',borderRadius:9,background:'rgba(255,255,255,.025)',marginTop:14},signal:{fontSize:20,marginTop:9},weak:{fontSize:12,color:DIM,lineHeight:1.6,marginTop:8},next:{marginTop:18,padding:22,border:'1px solid rgba(201,168,76,.28)',borderRadius:9,background:'rgba(201,168,76,.06)'},next h2:{},nextTitle:{fontSize:22},nextP:{},nextA:{},note:{fontSize:10,color:'rgba(247,244,238,.25)',textAlign:'center',marginTop:16},error:{marginTop:16,padding:12,border:'1px solid rgba(216,90,48,.3)',color:'#F09595',borderRadius:6,fontSize:12}
};
S.form.label={fontSize:10,fontWeight:700,letterSpacing:'.12em',color:'rgba(247,244,238,.55)',display:'grid',gap:6};
S.form.input={};
S.form['label input'],S.form['label select']={};
