import React, { useEffect, useMemo, useRef, useState } from "react";
import { BRAND } from "./assessmentLock.js";
import { EXPERIENCE_BANDS, TASTER_QUESTIONS, computeTasterResult, VALU_VERSION } from "./valuTaster.js";

const CLUSTERS={P:"Presence",R:"Relationships",I:"Intelligence",M:"Mastery",E:"Enterprise"};
const COLORS={P:"#1D9E75",R:"#378ADD",I:"#7F77DD",M:"#BA7517",E:"#D85A30"};
const shell={position:"fixed",inset:0,zIndex:1000,overflowY:"auto",background:"#0F0F1A",color:BRAND.PARCHMENT,fontFamily:"Raleway, sans-serif",padding:"clamp(28px,6vw,72px) 20px 64px"};
const wrap={width:"100%",maxWidth:720,margin:"0 auto"};
const eyebrow={fontSize:10,fontWeight:700,letterSpacing:".20em",color:"rgba(201,168,76,.72)"};
const input={width:"100%",boxSizing:"border-box",padding:"13px 14px",background:"rgba(255,255,255,.04)",border:"1px solid rgba(247,244,238,.12)",borderRadius:6,color:BRAND.PARCHMENT,fontFamily:"Raleway, sans-serif",fontSize:14,outline:"none"};
const button={width:"100%",border:0,borderRadius:6,padding:"16px 20px",background:BRAND.GOLD,color:"#0F0F1A",fontWeight:700,letterSpacing:".12em",fontSize:12,cursor:"pointer"};

function ExperienceSelect({value,onChange}){
  const [open,setOpen]=useState(false); const ref=useRef(null);
  useEffect(()=>{const outside=e=>{if(ref.current&&!ref.current.contains(e.target))setOpen(false)};document.addEventListener("mousedown",outside);return()=>document.removeEventListener("mousedown",outside)},[]);
  const selected=EXPERIENCE_BANDS.find(x=>x.id===value);
  return <div ref={ref} style={{position:"relative"}}>
    <button type="button" onClick={()=>setOpen(x=>!x)} aria-expanded={open} style={{...input,textAlign:"left",display:"flex",justifyContent:"space-between",alignItems:"center",background:"#171722",cursor:"pointer"}}><span style={{color:selected?BRAND.PARCHMENT:"rgba(247,244,238,.42)"}}>{selected?`${selected.label} · ${selected.desc}.`:"Select your experience."}</span><span>{open?"⌃":"⌄"}</span></button>
    {open&&<div role="listbox" style={{position:"absolute",zIndex:5,left:0,right:0,top:"calc(100% + 6px)",background:"#171722",border:"1px solid rgba(247,244,238,.14)",borderRadius:7,padding:6,boxShadow:"0 18px 40px rgba(0,0,0,.45)"}}>{EXPERIENCE_BANDS.map(x=><button key={x.id} type="button" onClick={()=>{onChange(x.id);setOpen(false)}} style={{width:"100%",border:0,borderRadius:5,padding:"11px 12px",background:x.id===value?"rgba(201,168,76,.12)":"transparent",color:x.id===value?BRAND.GOLD:BRAND.PARCHMENT,textAlign:"left",fontSize:13,cursor:"pointer"}}>{x.label} · {x.desc}.</button>)}</div>}
  </div>;
}

function ChoiceCard({active,title,eyebrowText,description,meta,onClick}){
 return <button type="button" onClick={onClick} aria-pressed={active} style={{width:"100%",textAlign:"left",padding:"18px",borderRadius:7,border:`1px solid ${active?"rgba(201,168,76,.55)":"rgba(247,244,238,.10)"}`,background:active?"rgba(201,168,76,.075)":"rgba(255,255,255,.025)",color:BRAND.PARCHMENT,cursor:"pointer"}}><div style={{display:"flex",justifyContent:"space-between",gap:12}}><div><div style={{...eyebrow,fontSize:9,color:active?BRAND.GOLD:"rgba(201,168,76,.48)",marginBottom:8}}>{eyebrowText}</div><div style={{fontSize:19,fontWeight:500,marginBottom:5}}>{title}</div><div style={{fontSize:11,lineHeight:1.55,color:"rgba(247,244,238,.43)",maxWidth:290}}>{description}</div></div><span style={{fontSize:18,color:active?BRAND.GOLD:"rgba(247,244,238,.25)"}}>→</span></div><div style={{display:"flex",gap:7,flexWrap:"wrap",marginTop:14}}>{meta.map(x=><span key={x} style={{fontSize:9,letterSpacing:".08em",padding:"5px 7px",border:"1px solid rgba(247,244,238,.08)",borderRadius:4,color:"rgba(247,244,238,.38)"}}>{x}</span>)}</div></button>;
}

export default function VALUIndexV4Gate({onComplete}){
 const [phase,setPhase]=useState("intro"),[name,setName]=useState(""),[role,setRole]=useState(""),[experience,setExperience]=useState(""),[type,setType]=useState("taster"),[current,setCurrent]=useState(0),[answers,setAnswers]=useState({}),[selected,setSelected]=useState(null),[results,setResults]=useState(null),[saving,setSaving]=useState(false),[failed,setFailed]=useState(false); const timer=useRef(null);
 const q=TASTER_QUESTIONS[current]; const canStart=!!(name.trim()&&role.trim()&&experience); const progress=Math.round(((current+1)/TASTER_QUESTIONS.length)*100); const scores=useMemo(()=>results?Object.entries(results.normalisedScores).sort((a,b)=>b[1]-a[1]):[],[results]);
 useEffect(()=>()=>timer.current&&clearTimeout(timer.current),[]);
 async function save(data){try{const r=await fetch("/api/submit-taster",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});return r.ok}catch{return false}}
 function start(){if(!canStart)return;setCurrent(0);setAnswers({});setSelected(null);setFailed(false);setPhase("taster")}
 async function answer(i){const next={...answers,[current]:i};setAnswers(next);if(current<TASTER_QUESTIONS.length-1){setTimeout(()=>{setCurrent(x=>x+1);setSelected(null)},420);return}setSaving(true);const r=computeTasterResult(next);setResults(r);const ok=await save({name:name.trim(),role:role.trim(),experience,answers:next});setSaving(false);setFailed(!ok);setPhase("results")}
 function choose(i){if(selected!==null)return;setSelected(i);timer.current=setTimeout(()=>answer(i),120)}
 if(phase==="intro") return <div style={shell}><div style={wrap}>
   <div style={{textAlign:"center",maxWidth:620,margin:"0 auto"}}><div style={{...eyebrow,display:"inline-block",padding:"7px 10px",border:"1px solid rgba(201,168,76,.20)",borderRadius:4}}>VALORIA INSTITUTE · AFRICAN TALENT BUREAU</div><h1 style={{fontFamily:"Georgia, 'Times New Roman', serif",fontWeight:400,fontSize:"clamp(42px,7vw,66px)",lineHeight:1.02,letterSpacing:"-.035em",margin:"16px 0 12px"}}>The <em style={{color:BRAND.GOLD}}>VALU</em> Index</h1><p style={{fontSize:14,lineHeight:1.75,color:"rgba(247,244,238,.58)",margin:0}}>Find out where you stand — and where your professional capabilities take you — in under 15 minutes.</p><p style={{fontSize:11,lineHeight:1.7,color:"rgba(247,244,238,.39)",maxWidth:560,margin:"12px auto 0"}}>A structured capability assessment built around the five PRIME dimensions: Professionalism, Relationships, Influence, Motivation &amp; Stamina, and Enterprise.</p></div>
   <div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:10,margin:"28px 0 18px"}}><ChoiceCard active={type==="taster"} eyebrowText="START HERE" title="TASTER" description="A short directional read across all five PRIME capability clusters." meta={[`${TASTER_QUESTIONS.length} questions`,`~5 minutes`,`Free`]} onClick={()=>setType("taster")}/><ChoiceCard active={type==="full"} eyebrowText="FULL ASSESSMENT" title="FULL VALU INDEX" description="The authoritative assessment used to establish your full VALU Index profile." meta={["58 questions","~15 minutes","Starts after taster"]} onClick={()=>setType("full")}/></div>
   <div style={{textAlign:"center",fontSize:11,color:"rgba(201,168,76,.68)",margin:"10px 0 22px"}}>The VALU Index is more than a test — it is your professional capability map.</div>
   <div style={{borderTop:"1px solid rgba(247,244,238,.08)",paddingTop:24}}><div style={{...eyebrow,marginBottom:6}}>YOUR DETAILS</div><p style={{fontSize:12,lineHeight:1.7,color:"rgba(247,244,238,.5)",margin:"0 0 18px"}}>Tell us a little about yourself so we can contextualise your assessment. These details do not change your score.</p><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12,marginBottom:18}}><label style={{...eyebrow,fontSize:9,display:"flex",flexDirection:"column",gap:7}}>FULL NAME<input value={name} onChange={e=>setName(e.target.value)} placeholder="Full name" style={input}/></label><label style={{...eyebrow,fontSize:9,display:"flex",flexDirection:"column",gap:7}}>CURRENT ROLE<input value={role} onChange={e=>setRole(e.target.value)} placeholder="e.g. Senior Marketing Manager" style={input}/></label><label style={{...eyebrow,fontSize:9,display:"flex",flexDirection:"column",gap:7,gridColumn:"1 / -1"}}>PROFESSIONAL EXPERIENCE<ExperienceSelect value={experience} onChange={setExperience}/></label></div>{type==="full"&&<div style={{padding:"11px 13px",marginBottom:14,borderRadius:6,border:"1px solid rgba(201,168,76,.18)",background:"rgba(201,168,76,.045)",fontSize:11,lineHeight:1.55,color:"rgba(247,244,238,.46)"}}><strong style={{color:BRAND.GOLD}}>Full VALU Index:</strong> the current v{VALU_VERSION} journey begins with the short taster. Your taster answers are not carried into the authoritative assessment.</div>}<button disabled={!canStart} onClick={start} style={{...button,opacity:canStart?1:.42,cursor:canStart?"pointer":"not-allowed"}}>{type==="full"?"START VALU JOURNEY →":"START THE FREE TASTER →"}</button><p style={{fontSize:11,lineHeight:1.6,color:"rgba(247,244,238,.27)",textAlign:"center",marginTop:16}}>Your experience band is profile metadata only. It does not affect your score. Assessment data is processed through the VALU v{VALU_VERSION} assessment flow.</p></div>
 </div></div>;
 if(phase==="taster") return <div style={shell}><div style={{...wrap,maxWidth:760}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:18}}><div style={eyebrow}>{q.cluster} · {CLUSTERS[q.cluster]}</div><div style={{fontFamily:"monospace",fontSize:12,color:"rgba(247,244,238,.35)"}}>{current+1} / {TASTER_QUESTIONS.length}</div></div><div style={{height:3,background:"rgba(255,255,255,.06)",marginBottom:30}}><div style={{height:"100%",width:`${progress}%`,background:COLORS[q.cluster]}}/></div><div style={{fontSize:11,color:"rgba(247,244,238,.42)",letterSpacing:".08em",marginBottom:14}}>{q.tasterInsight}</div><h2 style={{fontFamily:"Georgia, 'Times New Roman', serif",fontWeight:400,fontSize:"clamp(26px,4vw,40px)",lineHeight:1.15,margin:"0 0 30px",maxWidth:720}}>{q.q}</h2><div style={{display:"grid",gap:10}}>{q.options.map((o,i)=><button key={i} type="button" disabled={selected!==null} onClick={()=>choose(i)} style={{textAlign:"left",padding:"16px 18px",display:"grid",gridTemplateColumns:"28px 1fr",gap:12,alignItems:"start",borderRadius:7,border:`1px solid ${selected===i?BRAND.GOLD:"rgba(247,244,238,.10)"}`,background:selected===i?"rgba(201,168,76,.10)":"rgba(255,255,255,.025)",color:BRAND.PARCHMENT,cursor:"pointer",opacity:selected!==null&&selected!==i?.62:1}}><span style={{display:"flex",width:28,height:28,borderRadius:"50%",alignItems:"center",justifyContent:"center",border:`1px solid ${selected===i?BRAND.GOLD:"rgba(247,244,238,.18)"}`,color:selected===i?BRAND.GOLD:"rgba(247,244,238,.45)"}}>{selected===i?"✓":String.fromCharCode(65+i)}</span><span style={{fontSize:14,lineHeight:1.6}}>{o.text}</span></button>)}</div><div style={{minHeight:28,marginTop:18,fontSize:12,color:"rgba(247,244,238,.35)"}}>Select the answer that feels most like you.</div></div></div>;
 return <div style={shell}><div style={wrap}><div style={eyebrow}>VALU INDEX · TASTER COMPLETE</div><h1 style={{fontFamily:"Georgia, 'Times New Roman', serif",fontWeight:400,fontSize:"clamp(38px,7vw,62px)",lineHeight:1.05,margin:"16px 0"}}>{name}, here is your <em style={{color:BRAND.GOLD}}>directional read.</em></h1><p style={{fontSize:14,lineHeight:1.75,color:"rgba(247,244,238,.58)"}}>This is an early signal across all five PRIME clusters. It is not your full VALU Index score.</p>{failed&&<div style={{padding:14,margin:"18px 0",border:"1px solid rgba(201,168,76,.4)",borderRadius:7,fontSize:13}}>We could not save your taster result. Please retry before continuing.</div>}<div style={{display:"grid",gap:12,margin:"26px 0"}}>{scores.map(([id,score])=><div key={id}><div style={{display:"flex",justifyContent:"space-between",fontSize:13,marginBottom:5}}><span><b style={{color:COLORS[id]}}>{id}</b> · {CLUSTERS[id]}</span><span style={{color:COLORS[id]}}>{score}</span></div><div style={{height:6,background:"rgba(255,255,255,.06)"}}><div style={{height:"100%",width:`${score}%`,background:COLORS[id]}}/></div></div>)}</div><div style={{padding:20,background:`${COLORS[scores[0]?.[0]||"P"]}12`,border:`1px solid ${COLORS[scores[0]?.[0]||"P"]}40`,borderRadius:8,marginBottom:12}}><div style={eyebrow}>YOUR STRONGEST CLUSTER</div><div style={{fontSize:25,marginTop:6}}>{results?.strongest?.name}</div><p style={{fontSize:13,color:"rgba(247,244,238,.5)"}}>This is the capability signal to build from.</p></div><div style={{padding:20,background:"rgba(255,255,255,.025)",border:"1px solid rgba(201,168,76,.16)",borderRadius:8,marginBottom:24}}><div style={eyebrow}>YOUR BIGGEST OPPORTUNITY</div><div style={{fontSize:25,marginTop:6}}>{results?.weakest?.name}</div><p style={{fontSize:13,color:"rgba(247,244,238,.5)"}}>This is the clearest development opportunity in this taster.</p></div><button onClick={onComplete} disabled={saving||failed} style={{...button,opacity:saving||failed?.55:1}}>{saving?"SAVING YOUR READ…":failed?"SAVE FAILED — RETRY REQUIRED":"TAKE THE FULL VALU INDEX →"}</button><p style={{fontSize:11,lineHeight:1.6,color:"rgba(247,244,238,.27)",textAlign:"center",marginTop:16}}>The full VALU Index starts fresh. Your taster answers are not carried into the authoritative assessment.</p></div></div>;
}
